spring.application.name=tasks

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1

spring.datasource.username=system

spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.jpa.hibernate.ddl-auto=validate


jwt.secret = ${SECRET_KEY}

jwt.expiration.ms = 360000


status.completed.id=56420538DA8C0237E063020011ACD41C
